### PR TITLE
[PTT-241] Updated Payment model

### PR DESCRIPTION
**Pull request by infantesimone**
#### List of Changes

- added new fields to entity `PaymentPosition`: 
  - `total_options`;
  - `paid_options`;
  - `reported_options`.
- updated `PaymentPotitionModel` (and related mapper) to handle the new fields;
- initialized news fields:
  - `total_options` := total number of options;
  - `paid_options` := 0;
  - `reported_options` := 0.
- added new status for `PaymentPosition`:
  - `RENDICONTATO_PARZIALE(5)`,
  - `RENDICONTATO(6)`; 
- added new status for` PaymentPositionOptions`:
  - `RENDICONTATO(3)`,
- updated `TributeServiceModel` to the following spec:
   ```yaml
    TributeServiceModel:
      type: object
      properties:
        denomination:
          type: string
        dueDateUnique:
          type: string
          format: date
        fiscalCodePrimaryCreditor:
          type: string
        fiscalCodeSecondaryCreditor:
          type: string
        ibanPrimary:
          type: string
        ibanSecondary:
          type: string
        installments:
          type: array
          items:
            $ref: '#/definitions/InstallmentModel'
        percentageSecondary:
          type: number
        postalAuthCodePrimary:
          type: string
        postalAuthCodeSecondary:
          type: string
        postalIbanHolderPrimary:
          type: string
        postalIbanHolderSecondary:
          type: string
        postalIbanPrimary:
          type: string
        postalIbanSecondary:
          type: string
      title: TributeServiceModel
   ```
  

#### Motivation and Context

The goal of this PR is to update the data model for the payment position in order to implement the web services exposed to the node (`PartnerEndpoint`).

#### How Has This Been Tested?

- run application locally, according to `docker-compose-payment.yaml`:
- creare a payment position:
   1. POST /service-management/service
    ```json 
    {
      "denomination": "TARI",
      "dueDateUnique": "2021-07-01",
      "fiscalCodePrimaryCreditor": "77777777777",
      "fiscalCodeSecondaryCreditor": "77777777777",
      "ibanPrimary": "string",
      "ibanSecondary": "string",
      "installments": [
        {
          "dueDate": "2021-07-01",
          "percentagePrimary": 100,
          "percentageSecondary": 100
        }
      ],
      "percentageSecondary": 20
    }
    ```
  
    2. POST /payments/create
    ```json 
       {
       "csv": {
        "fileName": "fileName",
        "rows": [
          {
            "address": "string",
            "amount": 10,
            "area": "string",
            "cap": "string",
            "country": "st",
            "email": "string",
            "fiscalCode": "valid fiscal code",
            "idTenant": "string",
            "name": "string",
            "number": "string",
            "phone": "string",
            "province": "string",
            "reason": "string",
            "surname": "string",
            "type": 0
          }
        ]
      },
      "fiscalCodeCreditor": "77777777777",
      "jobId": 0
     }
    ```
- check payment position DB status, in particular:
  - `total_options` := total number of options;
  - `paid_options` := 0;
  - `reported_options` := 0. 

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pasqualespica — APPROVED** [review]
Great 👍 
One thing in this PR i'd fix the `postgres-user-test` value in the `.env.example` of `payments` too.
@infantesimone i'd a `resources` utility folder , if you think it will not be useful, delete it

**Review by GiovanniMancini — CHANGES_REQUESTED** [review]
Thank you @infantesimone . Maybe in this PR, as pointed out by @pasqualespica, we could add another requested change in the structure of the `transfer` entity: all the fields required to manage the case of an account from "Poste Italiane". In detail:
  - Intestazione_cc_postale : text
  - Cc_postale : text (which should be different from IBAN)
  - Codice_Autorizzazione_postale : text
 
Or do you think it's better to make them part of another PR?

**Comment by infantesimone** [comment]
@pasqualespica thanks, it's a useful tool for the first integration tests 🚀

**Comment by infantesimone** [comment]
Thanks @GiovanniMancini, I think it is consistent with the PR, but the requirement is not clear to me. For each `option` at least two `transfers`? one with `iban` and one with "Poste Italiane" references? so the DB should be updated like this?

AS-IS
asis

TO-BE
tobe

**Comment by GiovanniMancini** [comment]
@infantesimone @pasqualespica Yes this is what I meant. Maybe we should find better names ;-)

**Comment by infantesimone** [comment]
ok thanks, but is there documentation on these three new fields? I understand `cc_postale` but not `intestazione_cc_postale` and `codice_autorizzazione_postale`.

**Comment by GiovanniMancini** [comment]
@infantesimone In order to develop a deep understanding of the required fields, I think we should have a look to the following doc, in detail to the section 2.2 https://www.poste.it/resources/bancoposta/pdf/trasparenza/FI_BCCP.pdf as one of the use case to support is bills printing

**Comment by filma80** [comment]
Thank you @infantesimone for the great job.

We need to add in the entity transfers, other 2 fields `postalAuthCode` and` postalAccountholder`.
The new field must be updated with the values retrived by the service "`/service-management/service/{fiscalCodeEC}`" in the model `TributeServiceModel`) through the service `/create`.

It's necessary updated the following services for save and retrieve the new fileds from FrontEnd:

- microservice Service-management -> method `POST /service`
- microservice Service-management -> method `GET /service/{fiscalCode}`

**Review by filma80 — CHANGES_REQUESTED** [review]
Thank you @infantesimone for the great job.

We need to add in the entity transfers, other 2 fields `postalAuthCode` and` postalAccountholder`.
The new field must be updated with the values retrived by the service "`/service-management/service/{fiscalCodeEC}`" in the model `TributeServiceModel`) through the service `/create`.

It's necessary updated the following services for save and retrieve the new fileds from FrontEnd:

- microservice Service-management -> method `POST /service`
- microservice Service-management -> method `GET /service/{fiscalCode}`

**Review by GiovanniMancini — APPROVED** [review]

**Pull request merged**
